"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EOAuth2Scope = void 0;
var EOAuth2Scope;
(function (EOAuth2Scope) {
    EOAuth2Scope["OPENID"] = "openid";
    EOAuth2Scope["PROFILE"] = "profile";
    EOAuth2Scope["EMAIL"] = "email";
    EOAuth2Scope["ACCOUNT_READ"] = "account.read";
    EOAuth2Scope["ACCOUNT_WRITE"] = "account.write";
    EOAuth2Scope["DATA_READ"] = "data.read";
    EOAuth2Scope["DATA_WRITE"] = "data.write";
    EOAuth2Scope["DATA_CREATE"] = "data.create";
    EOAuth2Scope["DATA_DELETE"] = "data.delete";
    EOAuth2Scope["DATA_LIST"] = "data.list";
    EOAuth2Scope["ADMIN"] = "admin";
    EOAuth2Scope["MANAGE_SETTINGS"] = "settings.manage";
    EOAuth2Scope["MANAGE_USERS"] = "users.manage";
    EOAuth2Scope["MANAGE_PAYMENTS"] = "payments.manage";
    EOAuth2Scope["MANAGE_NOTIFICATIONS"] = "notifications.manage";
    EOAuth2Scope["SYSTEM_READ"] = "system.read";
    EOAuth2Scope["SYSTEM_WRITE"] = "system.write";
    EOAuth2Scope["SYSTEM_AUDIT"] = "system.audit";
    EOAuth2Scope["SYSTEM_REPORTS"] = "system.reports";
    EOAuth2Scope["SYSTEM_LOGS"] = "system.logs";
    EOAuth2Scope["FULL_ACCESS"] = "full_access";
    EOAuth2Scope["PAYMENTS_READ"] = "payments.read";
    EOAuth2Scope["PAYMENTS_WRITE"] = "payments.write";
    EOAuth2Scope["NOTIFICATIONS_READ"] = "notifications.read";
    EOAuth2Scope["NOTIFICATIONS_WRITE"] = "notifications.write";
})(EOAuth2Scope || (exports.EOAuth2Scope = EOAuth2Scope = {}));
//# sourceMappingURL=scope.oauth2.enum.js.map