export declare enum EScope {
    OPENID = "openid",
    PROFILE = "profile",
    EMAIL = "email",
    ACCOUNT_READ = "account.read",
    ACCOUNT_WRITE = "account.write",
    DATA_READ = "data.read",
    DATA_WRITE = "data.write",
    DATA_CREATE = "data.create",
    DATA_DELETE = "data.delete",
    DATA_LIST = "data.list",
    ADMIN = "admin",
    MANAGE_SETTINGS = "settings.manage",
    MANAGE_USERS = "users.manage",
    MANAGE_PAYMENTS = "payments.manage",
    MANAGE_NOTIFICATIONS = "notifications.manage",
    SYSTEM_READ = "system.read",
    SYSTEM_WRITE = "system.write",
    SYSTEM_AUDIT = "system.audit",
    SYSTEM_REPORTS = "system.reports",
    SYSTEM_LOGS = "system.logs",
    FULL_ACCESS = "full_access",
    PAYMENTS_READ = "payments.read",
    PAYMENTS_WRITE = "payments.write",
    NOTIFICATIONS_READ = "notifications.read",
    NOTIFICATIONS_WRITE = "notifications.write"
}
