"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EScope = void 0;
var EScope;
(function (EScope) {
    EScope["OPENID"] = "openid";
    EScope["PROFILE"] = "profile";
    EScope["EMAIL"] = "email";
    EScope["ACCOUNT_READ"] = "account.read";
    EScope["ACCOUNT_WRITE"] = "account.write";
    EScope["DATA_READ"] = "data.read";
    EScope["DATA_WRITE"] = "data.write";
    EScope["DATA_CREATE"] = "data.create";
    EScope["DATA_DELETE"] = "data.delete";
    EScope["DATA_LIST"] = "data.list";
    EScope["ADMIN"] = "admin";
    EScope["MANAGE_SETTINGS"] = "settings.manage";
    EScope["MANAGE_USERS"] = "users.manage";
    EScope["MANAGE_PAYMENTS"] = "payments.manage";
    EScope["MANAGE_NOTIFICATIONS"] = "notifications.manage";
    EScope["SYSTEM_READ"] = "system.read";
    EScope["SYSTEM_WRITE"] = "system.write";
    EScope["SYSTEM_AUDIT"] = "system.audit";
    EScope["SYSTEM_REPORTS"] = "system.reports";
    EScope["SYSTEM_LOGS"] = "system.logs";
    EScope["FULL_ACCESS"] = "full_access";
    EScope["PAYMENTS_READ"] = "payments.read";
    EScope["PAYMENTS_WRITE"] = "payments.write";
    EScope["NOTIFICATIONS_READ"] = "notifications.read";
    EScope["NOTIFICATIONS_WRITE"] = "notifications.write";
})(EScope || (exports.EScope = EScope = {}));
//# sourceMappingURL=scope.enum.js.map